const catalogue = [
  {
    id: 1,
    type: "product",
    category: "Dresses",
    name: "Floral Summer Dress",
    description: "Beautiful floral print dress perfect for summer outings. Lightweight and breathable fabric.",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80",
    priceLabel: "Ksh 2,500",
    price: 2500,
    badge: "New",
    available: true,
    specs: ["100% Cotton", "Breathable", "Machine Washable"],
  },
  {
    id: 2,
    type: "product",
    category: "Dresses",
    name: "Elegant Evening Gown",
    description: "Stunning evening gown for special occasions. Features a sleek silhouette with delicate embroidery.",
    image: "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800&q=80",
    priceLabel: "Ksh 5,500",
    price: 5500,
    badge: "Best Seller",
    available: true,
    specs: ["Silk Blend", "Floor Length", "Hand-Embroidered"],
  },
  {
    id: 3,
    type: "product",
    category: "Tops",
    name: "Casual Linen Blouse",
    description: "Lightweight linen blouse perfect for everyday wear. Available in multiple colors.",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    priceLabel: "Ksh 1,800",
    price: 1800,
    badge: null,
    available: true,
    specs: ["100% Linen", "Breathable", "Relaxed Fit"],
  },
  {
    id: 4,
    type: "product",
    category: "Tops",
    name: "Off-Shoulder Top",
    description: "Trendy off-shoulder top with elastic neckline. Pairs perfectly with jeans or skirts.",
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&q=80",
    priceLabel: "Ksh 1,500",
    price: 1500,
    badge: null,
    available: true,
    specs: ["Cotton Blend", "Elastic Neckline", "One Size"],
  },
  {
    id: 5,
    type: "product",
    category: "Bottoms",
    name: "High-Waist Trousers",
    description: "Elegant high-waist trousers with a wide-leg cut. Suitable for both office and casual wear.",
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80",
    priceLabel: "Ksh 2,200",
    price: 2200,
    badge: "New",
    available: true,
    specs: ["Polyester Blend", "Wide Leg", "High Waist"],
  },
  {
    id: 6,
    type: "product",
    category: "Bottoms",
    name: "Denim Mini Skirt",
    description: "Classic denim mini skirt with a modern twist. Features a button-front closure and belt loops.",
    image: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=800&q=80",
    priceLabel: "Ksh 1,600",
    price: 1600,
    badge: null,
    available: true,
    specs: ["Denim", "Button Front", "Belt Loops"],
  },
  {
    id: 7,
    type: "product",
    category: "Accessories",
    name: "Leather Crossbody Bag",
    description: "Genuine leather crossbody bag with adjustable strap and multiple compartments.",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
    priceLabel: "Ksh 3,200",
    price: 3200,
    badge: "Best Seller",
    available: true,
    specs: ["Genuine Leather", "Adjustable Strap", "Multiple Compartments"],
  },
  {
    id: 8,
    type: "service",
    category: "Tailoring",
    name: "Custom Dress Making",
    description: "Get a dress made to your exact measurements and design preferences. Consultation included.",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80",
    priceLabel: "From Ksh 3,000",
    price: 3000,
    badge: "Popular",
    available: true,
    includes: [
      "Free consultation & design session",
      "Professional measuring",
      "Premium fabric sourcing",
      "2 fitting sessions",
      "Alterations included",
    ],
  },
  {
    id: 9,
    type: "service",
    category: "Tailoring",
    name: "Alteration Service",
    description: "Professional clothing alterations including hemming, taking in/letting out, and repairs.",
    image: "https://images.unsplash.com/photo-1561144257-e32e8efc6c4f?w=800&q=80",
    priceLabel: "From Ksh 500",
    price: 500,
    badge: null,
    available: true,
    includes: [
      "Hemming (dresses, trousers, skirts)",
      "Taking in or letting out",
      "Zipper replacement",
      "Button replacement",
      "Quick turnaround",
    ],
  },
];

export default catalogue;
